

# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  CLEARDB_DATABASE_URL: 'mysql://ba3b9f164ba22d:e14b847a@eu-cdbr-west-02.cleardb.net/heroku_737b18bf53e9069?reconnect=true'
  CLEARDB_DATABASE_USERNAME: 'ba3b9f164ba22d'
  CLEARDB_DATABASE_PASSWORD: 'e14b847a'
steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
